<?php
/**
 * @package     Wright
 * @subpackage  Template File
 *
 * @copyright   Copyright (C) 2005 - 2016 Joomlashack. Meritage Assets.  All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */

// No direct access
defined('_JEXEC') or die('Restricted access');

?>
<doctype>
<html>
	<head>
		<w:head />
	</head>
	<body class="<?php echo $wrightBodyClass ?>">
		<?php
			if ($this->countModules('toolbar'))
				:
		?>
		<!-- toolbar -->
		<w:nav containerClass="<?php echo $wrightContainerClass ?>" rowClass="row-fluid" wrapClass="navbar-fixed-top navbar-inverse" type="toolbar" name="toolbar" />
		<?php
			endif;
		?>
		<div class="<?php echo $wrightContainerClass; ?> bg-color bg-color-two border-bottom-radius-large shadow  m-b-2 p-b-2 p-t-2">
			<!-- header -->
			<header id="header" class="m-b-2">
				<div class="row-fluid">
					<w:logo name="top" />
				</div>
			</header>
			<?php
				if ($this->countModules('menu'))
					:
			?>
			<!-- menu -->
	   	<w:nav name="menu" wrapper="m-b-2" />
			<?php
				endif;
			?>
			<div class="bg-color bg-color-white border-top-radius-large shadow p-b-0 clearfix">
				<!-- featured -->
				<?php
					if ($this->countModules('featured'))
						:
				?>
				<div id="featured" class="m-b-1">
					<w:module type="none" name="featured" />
				</div>
				<?php
					endif;
				?>
				<!-- grid-top -->
				<?php
					if ($this->countModules('grid-top'))
						:
				?>
				<div id="grid-top" class="items-bg">
					<w:module type="row-fluid" name="grid-top" chrome="wrightflexgrid" />
				</div>
				<?php
					endif;
				?>
				<?php
					if ($this->countModules('grid-top2'))
						:
				?>
				<!-- grid-top2 -->
				<div id="grid-top2" class="items-bg">
					<w:module type="row-fluid" name="grid-top2" chrome="wrightflexgrid" />
				</div>
				<?php
					endif;
				?>
				<div id="main-content" class="row-fluid m-b-2">
					<!-- sidebar1 -->
					<aside id="sidebar1">
						<w:module name="sidebar1" />
					</aside>
					<!-- main -->
					<section id="main">
						<?php
							if ($this->countModules('above-content'))
								:
						?>
						<!-- above-content -->
						<div id="above-content" class="items-bg">
							<w:module type="none" name="above-content" />
						</div>
						<?php
							endif;
						?>
						<?php
							if ($this->countModules('breadcrumbs'))
								:
						?>
						<!-- breadcrumbs -->
						<div id="breadcrumbs">
							<w:module name="breadcrumbs" chrome="none" type="none" />
						</div>
						<?php
							endif;
						?>
						<!-- component -->
						<w:content />
						<?php
							if ($this->countModules('below-content'))
								:
						?>
						<!-- below-content -->
						<div id="below-content" class="m-t-2 items-bg">
							<w:module type="none" name="below-content" />
						</div>
						<?php
							endif;
						?>
					</section>
					<!-- sidebar2 -->
					<aside id="sidebar2">
						<w:module name="sidebar2" />
					</aside>
				</div>
				<?php
					if ($this->countModules('grid-bottom'))
						:
				?>
				<!-- grid-bottom -->
				<div id="grid-bottom" class="items-bg">
					<w:module type="row-fluid" name="grid-bottom" chrome="wrightflexgrid" />
				</div>
				<?php
					endif;
				?>
				<?php
					if ($this->countModules('grid-bottom2'))
						:
				?>
				<!-- grid-bottom2 -->
				<div id="grid-bottom2" class="items-bg">
					<w:module type="row-fluid" name="grid-bottom2" chrome="wrightflexgrid" />
				</div>
				<?php
					endif;
				?>
			</div>
			<!-- footer -->
		  <footer class="bg-color bg-color-three border-bottom-radius-large shadow">
				<?php
					if ($this->countModules('bottom-menu'))
					:
				?>
				<!-- bottom-menu -->
				<w:nav containerClass="" rowClass="row-fluid" name="bottom-menu" wrapClass="navbar-inverse navbar-transparent" />
				<?php
					endif;
				?>

		   	<div class="footer-content">
			   	<?php
						if ($this->countModules('footer'))
						:
					?>
					<w:module type="row-fluid" name="footer" chrome="wrightflexgrid" />
				 	<?php
						endif;
					?>
					<w:footer />
				</div>
		  </footer>
	    <w:module type="none" name="debug" chrome="none" />
		</div>
	</body>
</html>
